### ISSUE TITLE
the environment ero

### ISSUE THREAD

**Issue by xiaoxiongfeng** [alexcg1/example-pdf-search#4]
I use my environment,  this project is ok; but I want to use a new environment by  requirements.txt, it have ero

- jina 3.3.6
- docarray 0.13.19
- jina-proto 0.1.8
- jina-vcs-tag (unset)
- protobuf 3.20.0
- proto-backend cpp
- grpcio 1.46.3
- pyyaml 6.0
- python 3.8.0
- platform Linux
- platform-release 5.4.0-73-generic
- platform-version #82-Ubuntu SMP Wed Apr 14 17:39:42 UTC 2021
- architecture x86_64
- processor x86_64
- uid 48062746421255
- session-id a624eecb-e704-11ec-a2c7-2bb67aed6807
- uptime 2022-06-08T16:26:09.280932
- ci-vendor (unset)
* JINA_ARRAY_QUANT (unset)
* JINA_CONTROL_PORT (unset)
* JINA_DEFAULT_HOST (unset)
* JINA_DEFAULT_TIMEOUT_CTRL (unset)
* JINA_DISABLE_UVLOOP (unset)
* JINA_FULL_CLI (unset)
* JINA_HUBBLE_REGISTRY (unset)
* JINA_HUB_CACHE_DIR (unset)
* JINA_HUB_ROOT (unset)
* JINA_GATEWAY_IMAGE (unset)
* JINA_LOG_CONFIG (unset)
* JINA_LOG_LEVEL (unset)
* JINA_LOG_NO_COLOR (unset)
* JINA_LOG_WORKSPACE (unset)
* JINA_MP_START_METHOD (unset)
* JINA_OPTIMIZER_TRIAL_WORKSPACE(unset)
* JINA_DEPLOYMENT_NAME (unset)
* JINA_RANDOM_PORT_MAX (unset)
* JINA_RANDOM_PORT_MIN (unset)
* JINA_VCS_VERSION (unset)

Traceback (most recent call last):
  File "app.py", line 184, in <module>
    main()
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "app.py", line 174, in main
    index(num_docs=num_docs)
  File "app.py", line 105, in index
    print(chunks[0].content)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/docarray/array/mixins/getitem.py", line 52, in __getitem__
    return self._get_doc_by_offset(int(index))
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/docarray/array/storage/memory/getsetdel.py", line 55, in _get_doc_by_offset
    return self._data[offset]
IndexError: list index out of range

**Comment by xiaoxiongfeng** [comment]
indexer/rep-0@348585[E]:ValueError('Document[2011, 2012, 2013, 2014, 2636, 2637, 2638, 2639, 3409, 3410, 3411, 3412, 4034, 4035, 4036, 4037, 4038, 4039, 4040, 4041, 4663, 4664, 4665, 4666, 5436, 5437, 5438, 5439, 6061, 6062, 6063, 6064, 6065, 6066, 6067, 6068, 6690, 6691, 6692, 6693].embedding is None. Can not stack into `embeddings`.')
 add "--quiet-error" to suppress the exception details
Traceback (most recent call last):
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/jina/serve/runtimes/worker/__init__.py", line 136, in process_data
    return await self._data_request_handler.handle(requests=requests)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/jina/serve/runtimes/request_handlers/data_request_handler.py", line 109, in handle
    return_data = await self._executor.__acall__(
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/jina/serve/executors/__init__.py", line 247, in __acall__
    return await self.__acall_endpoint__(req_endpoint, **kwargs)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/jina/serve/executors/__init__.py", line 256, in __acall_endpoint__
    return func(self, **kwargs)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/jina/serve/executors/decorators.py", line 140, in arg_wrapper
    return fn(executor_instance, *args, **kwargs)
  File "/home/xxf/.jina/hub-package/zb38xlt4/executor.py", line 92, in search
    docs[traversal_left].match(self._index[traversal_right], **match_args)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/docarray/array/mixins/match.py", line 73, in match
    match_docs = darray.find(
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/docarray/array/mixins/find.py", line 192, in find
    _result = self._find(
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/docarray/array/storage/memory/find.py", line 90, in _find
    return self._find_nn(query, cdist, limit, normalization, metric_name)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/docarray/array/storage/memory/find.py", line 107, in _find_nn
    dists = cdist(query, self.embeddings, metric_name)
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/docarray/array/mixins/content.py", line 25, in embeddings
    return unravel(self, 'embedding')
  File "/home/xxf/.conda/envs/pdf/lib/python3.8/site-packages/docarray/math/ndarray.py", line 26, in unravel
    raise ValueError(
ValueError: Document[2011, 2012, 2013, 2014, 2636, 2637, 2638, 2639, 3409, 3410, 3411, 3412, 4034, 4035, 4036, 4037, 4038, 4039, 4040, 4041, 4663, 4664, 4665, 4666, 5436, 5437, 5438, 5439, 6061, 6062, 6063, 6064, 6065, 6066, 6067, 6068, 6690, 6691, 6692, 6693].embedding is None. Can not stack into `embeddings`.
